* Unreleased
** Changed
- Command org-gtd-show-all-next renamed to org-gtd-engage-next
- File org-gtd-agenda.el renamed to org-gtd-engage.el
* 3.0.0
** Functions exist to create your own hooks
Make GTD truly a part of your emacs experience.
** Minimum emacs version now 27.2
I can't find 27.1 anywhere.
** Support habits
org mode's habits now have a place here
** Organize menu has changed
- Habits have their place
- What used to be called "archive" is now called "knowledge"
- Modify project is now "Add to project"
** Massive API changes
- The package domain now is a better match for the domain language of GTD.
** Massive Data structure changes
- SCHEDULED and DEADLINE are intended to be used for things that have to start and things that have to end, respectively. V2 abused them, v3 is more respectful of how org-mode wants to work.
** Include horizons
- They can be displayed while clarifying.
- There's an optional organize-hook for areas of focus
- There's an agenda view for areas of focus
** You can create your own project templates and insert them while clarifying
* 2.0.0
** Complete overhaul of inbox processing
We now respect that emacs is a GUI and that the user must have complete control at all times. The flow also provides control to the user *PRIOR* to the user choosing the way to categorize this item.
** Create an actual info file usable within emacs
** state CANCELED rename to CNCL
Fits the four-letter pattern better. You'll need to do a search-and-replace in the files managed by ~org-gtd~, replacing "CANCELED" by "CNCL".
** Better refile target discovery and dupport for many refile targets
The code now looks for top-level headings with a property called ~ORG_GTD~ with possible values: ~Action~, ~Incubated~, ~Projects~, ~Scheduled~, ~Delegated~.
* 1.1.1
[2021-10-06 Wed]
** Bugfix in project canceling
The system would effectively skip over headings. Had to disable ~org-edna-mode~ while Ι am changing the states to CANCELED.
* 1.1.0
[2021-10-03 Sun]
** README
There's a new public function, ~(org-gtd-inbox-path)~, you should use this in your configuration instead of ~(org-gtd--path org-gtd-inbox-file-basename)~.
** canceling projects
- projects can be canceled by calling ~(org-gtd-cancel-project)~ on the top headline of the project
- projects can be canceled by calling ~(org-gtd-agenda-cancel-project)~ when the point is on the next task of the project on the agenda view.
** archiving projects
~(org-gtd-archive-complete-projects)~ now archives both completed and canceled projects.
* 1.0.4
[2021-09-19 Sun]
** Massive readme revamp
the readme was a cluttered mess, I've broken it down into a lot of subsections. I hope it will be easier to manage now.
** org-gtd-process-item-hooks
Based on an idea in https://github.com/Trevoke/org-gtd.el/discussions/54

There's now an available variable that you can use to extend and customize the behavior of item processing. If you come up with cool ideas, share them!
* 1.0.3
I dunno why this tag existed but we're skipping this I guess.
* 1.0.2
[2020-08-20 Thu]
** Fix inability to refile to incubate
While processing the inbox, it was impossible to refile to the incubate file properly.
This release fixes that bug.

To note:
If you haven't yet, make sure you go to the incubate file and set up some categories for yourself, e.g. `* To Read`, `* To Eat`, etc. ~org-gtd~ currently handles up to two headline levels, so you could do `* To Read` and `** Horror` if you wanted
