* 2.0.0
** [ACTION REQUIRED] state CANCELED rename to CNCL
Fits the four-letter pattern better. You'll need to do a search-and-replace in the files managed by ~org-gtd~, replacing "CANCELED" by "CNCL".
* 1.1.1
[2021-10-06 Wed]
** Bugfix in project canceling
The system would effectively skip over headings. Had to disable ~org-edna-mode~ while Ι am changing the states to CANCELED.
* 1.1.0
[2021-10-03 Sun]
** README
There's a new public function, ~(org-gtd-inbox-path)~, you should use this in your configuration instead of ~(org-gtd--path org-gtd-inbox-file-basename)~.
** canceling projects
- projects can be canceled by calling ~(org-gtd-cancel-project)~ on the top headline of the project
- projects can be canceled by calling ~(org-gtd-agenda-cancel-project)~ when the point is on the next task of the project on the agenda view.
** archiving projects
~(org-gtd-archive-complete-projects)~ now archives both completed and canceled projects.
* 1.0.4
[2021-09-19 Sun]
** Massive readme revamp
the readme was a cluttered mess, I've broken it down into a lot of subsections. I hope it will be easier to manage now.
** org-gtd-process-item-hooks
Based on an idea in https://github.com/Trevoke/org-gtd.el/discussions/54

There's now an available variable that you can use to extend and customize the behavior of item processing. If you come up with cool ideas, share them!
* 1.0.3
I dunno why this tag existed but we're skipping this I guess.
* 1.0.2
[2020-08-20 Thu]
** Fix inability to refile to incubate
While processing the inbox, it was impossible to refile to the incubate file properly.
This release fixes that bug.

To note:
If you haven't yet, make sure you go to the incubate file and set up some categories for yourself, e.g. `* To Read`, `* To Eat`, etc. ~org-gtd~ currently handles up to two headline levels, so you could do `* To Read` and `** Horror` if you wanted
