* Org GTD

This package tries to replicate as closely as possible the GTD workflow.
This package assumes familiarity with GTD.

This package provides a system that allows you to capture incoming things into an inbox, then process the inbox and categorize each item based on the GTD categories.  It leverages org-agenda to show today's items as well as the NEXT items.  It also has a simple project management system, which currently assumes all tasks in a project are sequential.

For a comprehensive instruction manual, see the documentation.
Either the info file or in the [[doc/]] directory of the repository.
Upgrade information is also available therein.
* Directory tree
- =dev= :: used as a jail environment. Spin up with ~$ HOME="dev/" emacs~.
- =doc= :: where the documentation lives
- =test= :: where the tests are
* Community
If you want help, you can open an issue right on Github.

You're also welcome to join my [[https://discord.gg/9UAXpCaVJb][discord server]] for all conversations related to org-gtd in particular and GTD in general. Many of the ideas for org-gtd came out of my reading the GTD book, and then reading some sections multiple times, but I am in no way an expert. Defining the GTD domain, which is to say, getting to clear nomenclature with clear actions, is still a work in progress.
* Animated demo of org-gtd
TK
