#+TITLE: Org GTD User Manual
:PREAMBLE:
#+AUTHOR: Aldric Giacomoni
#+EMAIL: trevoke@gmail.com
#+DATE: 2015-{{{year}}}
#+LANGUAGE: en

#+TEXINFO_DIR_CATEGORY: Emacs
#+TEXINFO_DIR_TITLE: Org GTD: (org-gtd)
#+TEXINFO_DIR_DESC: An opinionated GTD flow implemented in org-mode
#+TEXINFO_FILENAME: ../org-gtd.info
#+SUBTITLE: for version 2.2
#+TEXINFO_DEFFN: t
#+OPTIONS: H:3 num:3 toc:2
#+PROPERTY: header-args :eval never
#+MACRO: year (eval (format-time-string "%Y"))

Org GTD is an attempt to implement the GTD flow described in the GTD
book as faithfully as possible.

#+TEXINFO: @noindent
This manual is for Org GtD version 2.2

:END:
* Copying
:PROPERTIES:
:copying:  t
:END:
Copyright (C) 2018-{{{year}}} Aldric Giacomoni <trevoke@gmail.com>

You can redistribute this document and/or modify it under the terms
of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any
later version.

This document is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

* Setting up Org GTD
** Summary
:PROPERTIES:
:DESCRIPTION: quick intro to GTD
:END:
This package tries to replicate as closely as possible the GTD workflow (see diagram below).

This package, and this documentation, assume familiarity with the flow of GTD as described in the book.

This package provides a system that allows you to capture incoming things into an inbox, then process the inbox and categorize each item based on the GTD categories. It leverages org-agenda to show today's items as well as the NEXT items. It also has a simple project management system, which currently assumes all tasks in a project are sequential.
#+begin_example
                                    +-------+
                                    |"STUFF"|
                                    +---+---+
                                        |
                                    +---v---+
                                    |IN BOX |
                                    +---+----+
                                        |              Eliminate  +----------+
                                        |            +------------>   Trash  |
                                   +----v------+     |            +----------+
                                   |What is it?|     |
                                   +----+------+     |            +----------+
                                        |            | Incubate   |  Someday/|
                                        |            +------------>  Maybe   |
+----------+  YES (Multi-Step)   +------v------+  NO |            +----------+
| Projects <---------------------+    Is it    +-----+
+-+----^---+                     |  Actionable?|     | File       +----------+
  |    |   +----------------+    +------+------+     +------------>Reference |
  |    |        Review For  |           |                         +----------+
+-v----+---+     Actions    |           | YES
| Planning |                +----------->
+----------+                            |
                                  +-----v------+     Less than
                  Delegate        | What's the |     2 minutes     +--------+
                     +------------+Next Action?+-------------------> DO IT  |
                     |            +-------+----+                   +--------+
                     |                    |
                     |                    |  FOR ME
                     |                    |           Specific Date or Time
                     |                    +----------------------------+
                     |              ASAP  |                            |
                +----v-----+           +--v-------+              +-----v----+
                |          |           |          |              |          |
                |          |           |          |              |          |
                |          |           |          |              |          |
                |          |           |          |              |          |
                |          |           |          |              |          |
                +----------+           +----------+              +----------+
                 Waiting For           Next Actions                 Calendar
#+end_example
** Upgrading
:PROPERTIES:
:DESCRIPTION: How to upgrade your local setup across major versions
:END:
If you are installing and not upgrading, you can skip this section entirely and just go to the next section, [[*Installing]].
*** 2.2.0 <- 2.1.0
**** respect org-mode's org-reverse-note-order variable
The upgrade to =2.0.1= allowed addition of a task as the first task of an existing project while organizing a clarified item.
=2.0.2= allows the user to choose what they prefer. Correspondibly, it lets the =org-mode= variable ~org-reverse-note-order~ operate as it should. In your configuration, use:
#+begin_src emacs-lisp
  (setq org-reverse-note-order t)   ;; refile to the top of the list
  (setq org-reverse-note-order nil) ;; refile to the bottom of the list
#+end_src

Note that if you're upgrading straight from 2.0.0 you still need to make the adjustment to the TRIGGER for your project headings.

*** 2.1.0 <- 2.0.0
**** Update org-edna trigger
In order for project modification to work, you will need to go to every Project heading that you have. You will find the following:
#+begin_example
:PROPERTIES:
:TRIGGER: next-sibling todo!(NEXT)
:ORG_GTD: Projects
:END:
#+end_example

And you will need to update the trigger so it looks like this:
#+begin_example
:PROPERTIES:
:TRIGGER: relatives(forward-no-wrap todo-only 1 no-sort) todo!(NEXT)
:ORG_GTD: Projects
:END:
#+end_example

Now be sure to set the following variable in your config file, before org-gtd loads, to disable the loud warning:

#+begin_src emacs-lisp
(setq org-gtd-update-ack "2.1.0")
#+end_src

That is it! You're ready to add tasks to existing projects while processing the inbox.
*** 2.0.0 <- 1.1.x
**** Configuration
Org GTD now handles dependency loading more intelligently, so you no longer need the overly complicated setup of ~org-gtd~, ~org-agenda~ and ~org-capure~ in your config for dependency loading. You now only need ~org-gtd~. If you are using ~use-package~ then the following is the minimal config required.

#+begin_src elisp
  (use-package org-gtd :after 'org)
#+end_src

You no longer need to configure ~org-agenda-property-list~ yourself. Org GTD now manages the context with a macro, ~with-org-gtd-context~. Any prior configuration of this subpackage can be handled as you did before.

You no longer need to configure ~org-agenda-files~. Same reason as above. This allows you to use org-gtd without destroying your previous setup, and makes it easier to try org-gtd and then get rid of it if you don't like it.

You no longer need to configure ~org-agenda-custom-commands~. Now there's ~org-gtd-agenda-custom-commands~ to take the relay - see the variable documentation for more information.

The org-capture templates are now simplified and managed by ~org-gtd-capture-templates~. If you did not change the default configuration, then you can just remove what you had. Read the variable documentaton for further information.
***** Example upgrade
My org-gtd config for 1.x was as follows:
#+begin_src elisp
  (use-package org-gtd
    :after org
    :quelpa (org-gtd :fetcher github :repo "trevoke/org-gtd.el"
                     :commit "1.1.1" :upgrade t)
    :demand t
    :custom
    (org-gtd-directory "~/org-gtd")
    (org-agenda-property-list '("DELEGATED_TO"))
    (org-edna-use-inheritance t)
    :config
    (org-edna-load)
    :bind
    (("C-c d c" . org-gtd-capture)
     ("C-c d a" . org-agenda-list)
     ("C-c d p" . org-gtd-process-inbox)
     ("C-c d n" . org-gtd-show-all-next)
     ("C-c d s" . org-gtd-show-stuck-projects)
     :map org-gtd-process-map
     ("C-c c" . org-gtd-choose)))


  (use-package org-agenda
    :ensure nil
    :no-require t
    :after (org-gtd)
    :custom
    (org-agenda-skip-deadline-if-done t)
    (org-agenda-skip-scheduled-if-done t)
    (org-agenda-files `(,org-gtd-directory))
    (org-agenda-custom-commands '(("g" "Scheduled today and all NEXT items" ((agenda "" ((org-agenda-span 1))) (todo "NEXT"))))))

  (use-package org-capture
    :ensure nil
    :after org-gtd
    :config
    (setq org-capture-templates `(("i" "Inbox"
                                 entry (file ,(org-gtd--path org-gtd-inbox-file-basename))
                                 "* %?\n%U\n\n  %i"
                                 :kill-buffer t)
                                ("t" "Todo with link"
                                 entry (file ,(org-gtd--path org-gtd-inbox-file-basename))
                                 "* %?\n%U\n\n  %i\n  %a"
                                 :kill-buffer t))))
#+end_src

And my config for 2.0 is:
#+begin_src elisp
  (use-package org-gtd
    :after org
    :quelpa (org-gtd :fetcher github :repo "trevoke/org-gtd.el"
                     :commit "2.0.0" :upgrade t)
    :demand t
    :custom
    (org-gtd-directory "~/org-gtd")
    (org-edna-use-inheritance t)
    :config
    (org-edna-mode)
    :bind
    (("C-c d c" . org-gtd-capture)
     ("C-c d e" . org-gtd-engage)
     ("C-c d p" . org-gtd-process-inbox)
     ("C-c d n" . org-gtd-show-all-next)
     ("C-c d s" . org-gtd-show-stuck-projects)
     :map org-gtd-process-map
     ("C-c c" . org-gtd-choose)))
#+end_src
**** Relevant commands with new names
- ~org-agenda-list~ -> ~org-gtd-engage~
- ~org-gtd-clarify-finalize~ -> ~org-gtd-choose~ (see the section on Key bindings below)
**** heading states (TODO, etc.)
You need to rename CANCELED to CNCL. a simple string replace in the ~org-gtd-directory~ will do the trick.
**** Differentiating GTD types of items
Org GTD no longer uses the name of the heading to figure out how to refile things, and which headings are useful. Instead it uses a custom Org property called ORG_GTD. This means you are free to rename the existing headings whatever you want, but you DO need to make some adjustments to your current files.

If you would like to add new refile targets, it's simple, follow these instructions.

For projects, make sure the heading has the following two properties.
#+begin_src org-mode
:PROPERTIES:
:TRIGGER: next-sibling todo!(NEXT)
:ORG_GTD: Projects
:END:
#+end_src

For other headings, make sure there is an ORG_GTD property, like for the project, above.

The other ORG_GTD properties are set as follows. Note that Single and Delegated actions are together now, so you can merge those headings if you want.

- Scheduled actions :: =ORG_GTD: Calendar=
- Single & Delegated actions :: =ORG_GTD: Actions=
- Incubated actions :: =ORG_GTD: Incubated=

For incubated actions, version 1.x of Org GTD asked for second-level heading, such as ~*To Read~. No more - these are now top-level headings, exactly as described above, with a heading property of ~ORG_GTD: Incubated~.
**** Multiple refile targets
There is a new variable, ~org-gtd-refile-to-any-target~. By default this variable is set to ~t~. This means that Org GTD will refile to whatever the first target it finds is. This is the default value because it most closely matches the behavior for version 1.x.
*THIS BEHAVIOR ALSO APPLIES TO INCUBATE REFILE TARGETS*. Therefore, if you have multiple incubated refile targets, you will need to set this variable to ~nil~, or change to a single refile target. You can e.g. set a custom property to describe the kind of incubated item it is, if it is useful to you, something like:

#+begin_example
,* Incubated
,** Buy a boat
SCHEDULED: <2035-06-01 Fri>
:PROPERTIES:
:INCUBATE: big financial investment
:END:
#+end_example
**** Key bindings
Version 1.x of Org GTD recommended a binding for ~org-gtd-clarify-finalize~. This binding must now be set as follows (replace the keybinding with one of your choice):

#+begin_src elisp
  (define-key org-gtd-process-map (kbd "C-c c") #'org-gtd-choose)
#+end_src
** Installing
:PROPERTIES:
:DESCRIPTION: Get Org GTD in your emacs
:END:
This package requires emacs 27.1 or higher.

This package is on MELPA and MELPA stable under the name ~org-gtd~.
*** use-package
Just make sure this is loaded after ~org-mode~ like so.
#+begin_src emacs-lisp
  (use-package org-gtd :after org)
#+end_src
*** Manually
Check out the source code for dependencies and install them.
Then, clone this repo to a directory of your choice, e.g. =~/.emacs.d/packages=.
Finally, add this to your config:
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/packages")
(require 'org-gtd)
#+end_src
** Configuring
:PROPERTIES:
:DESCRIPTION: Required and optional system configuration
:END:
*** The easy way
Just turn on ~org-gtd-mode~ (~M-x org-gtd-mode~). This will set up emacs, Org mode, and Org GTD's dependencies. It will wrap a number of ~org-agenda~ functions to work smoothly. If you are just testing out Org GTD, this is a good way to start.

Turn off ~org-gtd-mode~ to restore emacs to pre-org-gtd settings.

Note, you should still head over to the [[*Recommended key bindings]] section.
*** Required configuration of sub-packages
**** org-edna
package: https://www.nongnu.org/org-edna-el/

This is one of the dependencies. This setting change is REQUIRED. It automatically changes the next TODO heading to NEXT in a project when you've finished the current task.

You do not need to make this change if you choose to toggle ~org-gtd-mode~.
#+begin_src emacs-lisp
(setq org-edna-use-inheritance t)
(org-edna-mode 1)
#+end_src
*** configuration options for org-gtd
**** I don't care, just let me start using it
The most direct way to find out about the configuration options for org-gtd is to see the customize group: ~M-x customize-group RET org-gtd~. They are all optional because they all come with default values.

The only one you may want to change before starting to use Org GTD is ~org-gtd-directory~, which is the directory that Org GTD
will look to for everything it needs to do.

The configuration options will also be mentioned in the relevant subsections of [[*Using Org GTD]].
**** Tell me all the levers I can pull

Make sure you also read about sub-package configuration: [[*Required configuration of sub-packages]].

- ~org-gtd-directory~ :: set this to a directory. =org-gtd= will look for all its files in this directory.
- ~org-gtd-capture-templates~ :: (!note: take care when changing this) This defines the pre-filled text that will show up when capturing an item to the inbox. This is a simplified version of ~org-capture-templates~. If you want to modify it, you should be able to get away with only reading the documentation for this one variable. The only recommendation is that the template string must define an org-mode top-level heading. That is to say, the first two characters must be a single asterisk followed by a space: "* ". [[*Adding things to the inbox]].
- ~org-gtd-agenda-custom-commands~ :: (!note: take care when changing this) this is the exact same thing as ~org-agenda-custom-commands~. =Org-gtd= requires that the key =g= be bound to a display view, so if you want to change what =org-gtd= displays, make sure you leave the =g= alone (or modify that one). [[*Engaging with your GTD items]].
- ~org-reverse-note-order~ :: (=org-mode= variable) set this to ~t~ to add new items to the top of project tasks and to ~nil~ to add new items to the bottom of project tasks. Most relevant, see [[*Projects]] and [[*Modify an existing project]].
- ~org-gtd-process-item-hooks~ :: this is a list of functions that you can use to decorate each item when you clarify it. For instance, you could add a function to set the effort, or the priority, or some category, etc. By default it has only one function, which lets you add tags. You could remove this function if you wanted. [[*Processing the inbox]].
- ~org-gtd-archive-location~ :: variable that holds a function to generate the archive file. I made this choice primarily because I want to refile to an archive file suffixed with the year, and I'm *just too lazy* to manually rename them once a year. The function has an arity of zero and generates an org-mode file+outline path. [[*Cleaning up / archiving completed work]].
- ~org-gtd-refile-to-any-target~ :: when ~t~, =org-gtd= will refile to the first target it finds, and create a target if it doesn't find one. When false, it will ask for confirmation before refiling. [[*Multiple files / refile targets]].
- ~org-gtd-delegate-read-func~ :: function that is used to prompt for a person a task is delegated to. Must return a string. By default this is set to ~read-string~.
*** Recommended key bindings

There's an important keymap you'll want to make the flow of processing the inbox smoother. To limit impact on your emacs configuration, there is a specific keymap you can use. The function you'll want to bind is ~org-gtd-choose~. I suggest ~C-c c~, as in the following example.

#+begin_src elisp
(define-key org-gtd-process-map (kbd "C-c c") #'org-gtd-choose)
#+end_src

For other keybindings, do what you need. My bindings use ~C-c d~ as a prefix, i.e.:

- ~C-c d c~ :: ~org-gtd-capture~
- ~C-c d e~ :: ~org-gtd-engage~

etc.

* Using Org GTD
:PROPERTIES:
:DESCRIPTION: How Org GTD maps to the GTD flow
:END:

Here are the categories of actions from GTD that we have to be able to handle:

- adding things to the inbox
- processing the inbox
- Engage with your GTD system
- cleaning up / archiving completed work

Other elements of GTD, such as reviews, are currently unimplemented: as the user, you can simply open the files to review things for now.

** Adding things to the inbox

The inbox is a file called ~inbox.org~ in the directory stored in the variable ~org-gtd-directory~. By default this variable is ~~/gtd~.

Org GTD provides one function to capture items: ~M-x org-gtd-capture~. In my setup I have this booked globally as such:

#+begin_src elisp
(global-set-key "C-c d c" #'org-gtd-capture)
#+end_src

This function overrides ~org-capture~ and uses the variable ~org-gtd-capture-templates~ to define org-gtd-specific capture templates. By default it comes with two templates, one to just capture a new item, and one to capture an item with a link to the file where you were when you started the capture.

** Processing the inbox
Processing the inbox means taking everything in the inbox, one at a time, and refining/categorizing them so they are instantly useful when you are looking at available next / scheduled actions.

You can start processing the inbox with ~org-gtd-process-inbox~. This will select the inbox buffer and hide everything but the first item in the inbox, then give you control to refine it.

When you are done refining it, call ~M-x org-gtd-choose~ (or hit your keybinding for it, see [[*Recommended key bindings]]). This will open a transient menu to let you choose how Org GTD should categorize this item.

You have a number of possible choices for each item you process. Subsections will explain how Org GTD handles each one.

- *[P]rojects :: This is a multi-step action. [[*Projects]].
- *[M]odify a project :: Add current task to pre-existing project. [[*Modify an existing project]].
- *[Q]uick action :: Less than 2 minutes. Do it now, then choose this to mark the item as DONΕ and archive it. [[*Quick action]].
- *[T]rash* :: Not actionable; not knowledge. [[*Trash]].
- *[C]alendar* :: Single action to be done at a given date or time. [[*Calendar]].
- *[D]elegate :: Let someone else do this. [[*Delegate]].
- *[S]ingle action* :: This is a one-off to be done when possible. [[*Single action]].
- *[A]rchive* :: This is knowledge to be stored away. [[*Archive]].
- *[I]ncubate* :: no action now; review later. [[*Incubate]].

In addition you have *[x]* for "exit early", which you can use to stop processing the inbox and restore emacs to its non-inbox-processing state.

After the item-type-specific behavior, you will have the option to add custom decorations to each item, based on how you prefer to think about (filter, find, etc.) the items when you do GTD.

This process will continue, item after item, until you hit *x* to exit early or until you run out of items to process.

The decorations (priority, tags, categories, etc.) are customizable as you desire and managed by ~org-gtd-process-item-hooks~, a list of functions. By default there is one element in the list, to add tags to the item. You can add your own functions to this list, as long as the functions do not modify the text in any "custom" way, separate from what org-mode understands.
*** Projects
A "project" in GTD is a finite set of steps after which a given task is complete. In Org GTD, this is defined as a top-level org heading with a set of second-level org headings. Those second-level headings represent the sequentially-ordered set of tasks to be executed before the project can be called complete.
When the item you are editing is intended to be a project, create such a headline structure, like so:

#+begin_example
,* Project heading
,** First task
,** Second task
,** Third task
#+end_example

Then call ~M-x org-gtd-choose~ or hit your chosen keybinding, tell Org GTD you chose a project, and move on to the next item in the inbox.

A project is defined as "completed" when all its tasks are marked as DONE.
A project is defined as "canceled" when its last task is marked as CNCL.

You can cancel a project by calling ~org-gtd-agenda-cancel-project~ from the agenda view, when the point is on the next task of the project.

DO NOTE: it is surprisingly difficult to add a custom note when canceling, so if you want to add a note explaining why you canceled the project, you will have to do so manually.

Projects will show up in the agenda, but only the current NEXT task.
*** Modify an existing project
When you choose this, the package will do the following:
- refile this as a task inside the project of the project (first or last, depending on value of ~org-reverse-note-order~)
- adjust the TODO keywords of the project such that:
  - all DONE or CNCL keywords are untouched
  - there is exactly one WAIT or NEXT keyword
  - all other keywords are TODO

You can go to that project yourself and readjust the order of the headings as necessary, and then you can go to that project's top heading ("Project heading" in example below) and execute ~M-x org-gtd-projects-fix-todo-keywords-for-project-at-point~

#+begin_example
,* Project heading
,** NEXT First task
,** TODO Second task
,** TODO Third task
#+end_example
*** Quick action
When you choose quick action, you indicate that not much more tracking is necessary. This item is automatically marked as DONE and archived, then Org GTD moves on to the next item.

This won't show up in the agenda, because you've already done it.
*** Trash
When you choose trash, the item is automatically marked as CNCL and archived, then Org GTD moves on to the next item.

This won't show up in the agenda, because you don't care about it.
*** Calendar
When you you choose calendar, you will be asked to select a date (and time if you choose to add it), then Org GTD moves on to the next item.
This will come up in the agenda when the time is right. Literally.
*** Delegate
When you choose delegate, you'll be asked for a name to whom to delegate this to, and a date on which to check in with the person. Org GTD automatically marks this item as "WAIT", then Org GTD moves on to the next item.

This will show up in the "Blocked" section of the agenda.
*** Single action
When you choose single action, Org GTD will mark it as a NEXT item, then Org GTD moves on to the next item.

This will show up in the agenda as a NEXT item.
*** Archive
When you choose archive, Org GTD will assume you have done what you needed to do to store this (e.g. put the information in org roam, bbdb, or wherever you will store it), then marks the item as DONE and archives it. Org GTD then moves on to the next item.

This won't show up in the agenda because it's not actionable.
*** Incubate
Incubating an item is similar to simply scheduling one, though the idea is that you want to be reminded of it much later, and be able to review your incubated items separately.
So, all this will really do is make you choose a date at which you want to be reminded of this, then it'll be refiled under an incubated target.

This will show up in the agenda at the date of your choosing.
** Engaging with your GTD items
You can see a list of all NEXT actions, and scheduled actions, with ~M-x org-gtd-engage~ . This opens an ~org-agenda~ view.

The variable ~org-gtd-agenda-custom-commands~ has the settings to define what gets shown in that function.

You can define other functions by adding new custom commands to the above, and defining your own functions like so, where "x" is whatever your defined key is.

#+begin_src elisp
  (defun my-agenda ()
    (with-org-gtd-context
        (org-agenda nil "x")))
#+end_src

You can call ~org-gtd-show-all-next~ to only see NEXT actions, nothing scheduled.

Org Gtd uses ~org-edna~ to automatically trigger state changes in projects, such that when you mark a NEXT item from a project as DONE, the next TODO in that project automatically becomes NEXT, such that the agenda is always up-to-date (you may need to refresh the agenda).

*** Interacting with org-agenda
Since Org provides the agenda, it is a convenient base of operations for interacting with things that come up through ~org-gtd-engage~.

Here are the actions available to you:

- ~M-x org-gtd-agenda-cancel-project~ :: When the point is on a project action, this command will cancel the remaining actions in the project.
- ~M-x org-gtd-agenda-delegate~ :: When the point is on an action, this will properly delegate the action to someone else.
- ~M-x org-gtd-agenda-projectify~ :: This is intended to be used on an incubated item that has come up. Behavior in other situations has not been tested. This will properly let you transform an incubated item into a project.
- ~M-x org-gtd-agenda-single-action~ :: This is intended to be used on an incubated item that has come up. Behavior in other situations has not been tested. This will properly let you transform an incubated item into an action.
- ~M-x org-gtd-agenda-trash :: This will trash the current agenda item
- ~M-x org-gtd-agenda-quick-action :: This will mark the current agenda item as done and archive it

** Cleaning up / archiving completed work
Doing this without user intervention is tricky, as it makes undoing actions more complicated. As such, Org GTD provides a function that will go through the ~org-gtd-directory~ files, find the headings that belong to Org GTD (see [[*Multiple files / refile targets]]), and archive the finished items.

The variable ~org-gtd-archive-location~ hosts a *function* that returns a string matching the ~org-archive-location~ definition. It is a function in order to make the filename entirely dynamic.

The function to archive everything is ~M-x org-gtd-archive-completed-items~.
** Multiple files / refile targets
If you would like to add new refile targets, it's simple, follow these instructions.
*** New project heading
Add a top-level heading in any ~.org~ file (including a new one) in ~org-gtd-directory~ and make sure it has the following properties drawer.
#+begin_src org-mode
:PROPERTIES:
:TRIGGER: relatives(forward-no-wrap todo-only 1 no-sort) todo!(NEXT)
:ORG_GTD: Projects
:END:
#+end_src
*** Other headings
Create a new top-level heading in any ~.org~ file (including a new one) and make sure it has an ORG_GTD property as such.
#+begin_src org-mode
:PROPERTIES:
:ORG_GTD: Action
:END:
#+end_src

The ORG_GTD properties are set as follows, except for Projects (see [[*New project heading]]):

- Scheduled actions :: =ORG_GTD: Calendar=
- Incubated actions :: =ORG_GTD: Incubated=
- Single & Delegated actions :: =ORG_GTD: Actions=
* Troubleshooting
** Projects without a NEXT item
Sometimes things break. Use ~M-x org-gtd-show-stuck-projects~ to find all projects that don't have a NEXT item, which is to say, all projects that the package will not surface and help you finish.

~org-edna~ needs to be configured and enabled, see [[*Required configuration of sub-packages]].

To fix such a stuck project, put the point on the project heading and call ~M-x org-gtd-projects-fix-todo-keywords-for-project-at-point~.
** I can't create a project when clarifying an inbox item!
[[*Projects]]. If this does not help you, please open an issue and show exactly what you have done before asking =org-gtd= to create a project.
