#+TITLE: Org GTD User Manual
:PREAMBLE:
#+AUTHOR: Aldric Giacomoni
#+EMAIL: trevoke@gmail.com
#+DATE: 2015-{{{year}}}
#+LANGUAGE: en

#+TEXINFO_DIR_CATEGORY: Emacs
#+TEXINFO_DIR_TITLE: Org GTD: (org-gtd)
#+TEXINFO_DIR_DESC: An opinionated GTD flow implemented in org-mode
#+TEXINFO_FILENAME: ../org-gtd.info
#+SUBTITLE: for version 4.0.0
#+TEXINFO_DEFFN: t
#+OPTIONS: H:3 num:3 toc:2
#+PROPERTY: header-args :eval never
#+MACRO: year (eval (format-time-string "%Y"))

Org GTD is an attempt to implement the GTD flow described in the GTD
book as faithfully as possible.

#+TEXINFO: @noindent
This manual is for Org GTD version 4.0.0

:END:
* Copying
:PROPERTIES:
:copying:  t
:END:
Copyright (C) 2018-{{{year}}} Aldric Giacomoni <trevoke@gmail.com>

You can redistribute this document and/or modify it under the terms
of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any
later version.

This document is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

* Summary
:PROPERTIES:
:DESCRIPTION: quick intro to GTD
:END:
This package tries to replicate as closely as possible the GTD workflow (see diagram below).

This package, and this documentation, assume familiarity with the flow of GTD as described in the book.

This package provides a system that allows you to capture incoming things into an inbox, then process the inbox and categorize each item based on the GTD categories. It leverages org-agenda to show today's items as well as the NEXT items. It provides a flexible project management system with support for both sequential and parallel task execution.

*New to org-gtd?* Start with [[#getting-started][Getting Started with Org GTD]] for a hands-on tutorial.

*Upgrading from 3.x?* See [[#upgrading][Upgrading]] for required configuration changes and migration steps.
#+begin_example
                                    +-------+
                                    |"STUFF"|
                                    +---+---+
                                        |
                                    +---v---+
                                    | INBOX |
                                    +---+---+
                                        |              Eliminate  +-----------+
                                        |            +----------->|  Trash    |
                                 +------v------+     |            +-----------+
                                 | What is it? |     |
                                 +------+------+     |            +-----------+
                                        |            | Incubate   |  Someday/ |
                                        |            +----------->|   Maybe   |
+----------+  YES (multi-step)   +------v------+  NO |            +-----------+
| Projects |<--------------------|    Is it    |-----+
+-+----^---+                     | Actionable? |     | File       +-----------+
  |    |   +----------------+    +------+------+     +----------->| Reference |
  |    |        Review for  |           |                         +-----------+
+-v----+---+     Actions    |           |
| Planning |                +---------->| YES
+----------+                            |
                                 +------v------+     Less than
                       Delegate  | What's the  |     2 minutes    +-----------+
                     +-----------+    NEXT     +----------------->|   DO IT   |
                     |           |   Action?   |                  +-----------+
                     |           +------+------+
                     |                  |
                     |                  | FOR ME:
                     |                  |         Specific Date or Time
                     |                  +-------------------------------+
                     |              ASAP|                               |
               +-----v-----+      +-----v-----+                   +-----v-----+
               |           |      |           |                   |           |
               |           |      |           |                   |           |
               |           |      |           |                   |           |
               |           |      |           |                   |           |
               |           |      |           |                   |           |
               +-----------+      +-----------+                   +-----------+
                Waiting For        Next Actions                      Calendar
#+end_example

#+INCLUDE: "whats-new-5.0.org"

#+INCLUDE: "whats-new-4.0.org"

#+INCLUDE: "setting-up-org-gtd.org"

#+INCLUDE: "getting-started-with-org-gtd-manual-section.org"

#+INCLUDE: "using-org-gtd.org"

#+INCLUDE: "reference.org"

#+INCLUDE: "extending-org-gtd.org"

#+INCLUDE: "troubleshooting.org"
